apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # port of the backend
      port: 80 # port of the service
  selector: # link the service to a set of pods
    app: mapp # label of the pod
    type: front-end # label of the pod