apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end # also tier instead of type?
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template: # the part below is the pod defintion yaml. see pod-defintion.yaml in the folder 08-Pods
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx